### ISSUE TITLE
Storybook導入する

### ISSUE THREAD

**Issue by kano-yuko** [YukoKano/blog#3]

**Comment by kano-yuko** [comment]
https://storybook.js.org/tutorials/intro-to-storybook/

**Comment by YukoKano** [comment]
Chromaticも導入した

CIにも組み込めるらしい
https://www.chromatic.com/docs/ci/

**Comment by YukoKano** [comment]
https://qiita.com/ogakuzuko/items/d9ae8461fb8dd0bc866b

**Comment by YukoKano** [comment]
Chromatic も同時に調べる
